server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhilashk12/ecommerce-config-repo.git

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}